spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/the_babk_database
    username: main_gateway
    password: password123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

port: 8080
